package reviewdog

type AutoGenerated struct {
	Source      Source        `json:"source"`
	Severity    string        `json:"severity"`
	Diagnostics []Diagnostics `json:"diagnostics"`
}
type Source struct {
	Name string `json:"name"`
	URL  string `json:"url"`
}
type Start struct {
	Line   int `json:"line"`
	Column int `json:"column"`
}
type Location struct {
	Path  string `json:"path"`
	Range Range  `json:"range"`
}
type Code struct {
	Value string `json:"value"`
	URL   string `json:"url"`
}
type End struct {
	Line   int `json:"line"`
	Column int `json:"column"`
}
type Range struct {
	Start Start `json:"start"`
	End   End   `json:"end"`
}
type Suggestions struct {
	Range Range  `json:"range"`
	Text  string `json:"text"`
}
type Diagnostics struct {
	Message     string        `json:"message"`
	Location    Location      `json:"location"`
	Severity    string        `json:"severity"`
	Code        Code          `json:"code,omitempty"`
	Suggestions []Suggestions `json:"suggestions,omitempty"`
}
